set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)

set(RISC0_TOOLCHAIN_PATH "$ENV{RISC0_TOOLCHAIN_PATH}" CACHE STRING "RISC0 toolchain path")

set(CMAKE_SYSROOT ${RISC0_TOOLCHAIN_PATH}/riscv32-unknown-elf)

set(CMAKE_C_COMPILER ${RISC0_TOOLCHAIN_PATH}/bin/riscv32-unknown-elf-gcc)
set(CMAKE_CXX_COMPILER ${RISC0_TOOLCHAIN_PATH}/bin/riscv32-unknown-elf-g++)
set(CMAKE_AR ${RISC0_TOOLCHAIN_PATH}/bin/riscv32-unknown-elf-ar)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

message(STATUS "Using toolchain: ${CMAKE_TOOLCHAIN_FILE}")
